### ISSUE TITLE
Android Warning: new NativeEventEmitter()

### ISSUE THREAD

**Issue by lranches-gemini** [jk-gan/redux-flipper#56] opened 2021-09-23 20:08 UTC
Getting a console warning for only android when enabling the redux-flipper middleware. If I remove the middleware, the warning does go away.

react-native: 0.65.1
react-native-flipper: 0.110.0
redux-flipper: 2.01

<img width="382" alt="Screen Shot 2021-09-23 at 12 59 23 PM" src="https://user-images.githubusercontent.com/89813159/134576548-cec1549c-ec31-40c4-adb7-ab982efb5f63.png">

**Comment by plwai** [comment] 2021-09-24 06:25
This is caused by the native module `react-native-flipper`. There is nothing can be done by here so far. Can let this issue open until the problem fixes.

https://github.com/facebook/flipper/issues/2707

**Comment by bell-steven** [comment] 2021-11-14 23:18
Fixed in Flipper [v0.119.0](https://github.com/facebook/flipper/releases/tag/v0.119.0)

**Closed** 2021-11-20 09:13 UTC
