### ISSUE TITLE
Plugin not working on iOS after migrating to Flipper 0.164.0

### ISSUE THREAD

**Issue by simonkarmy** [jk-gan/redux-flipper#68] opened 2022-09-25 06:43 UTC
I am facing a problem once I migrated to the latest flipper 0.164.0
It is working normally with Android, but in iOS it is always showing 
`Plugin 'Redux Debugger' is not supported by the selected application 'XYZ' (iOS).`

it was working normally when I was working with flipper 0.145.0
```
"dependencies": {
    ......
    "react-native": "0.66.4",
    "react-native-flipper": "^0.164.0",
    "redux-flipper": "^2.0.2",
    ......
}
```

I have run pod install multiple times with no hope, keeping in mind other parts from flipper is working normally

**Comment by plwai** [comment] 2022-09-27 15:40
@jk-gan

**Comment by Woutwo** [comment] 2022-09-27 18:58
I also have this issue. The error message I see is:
```
WARN  The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed as yarn dependency to your project and, for iOS, that `pod install` is run in the `ios` directory.
```

**Comment by machadogj** [comment] 2022-09-30 22:52
Same error message as OP with very similar config:

```
    "react-native": "0.66.3",
    "react-native-flipper": "^0.164.0",
    "redux-flipper": "^2.0.2",
```

I also have this error message in the Flipper logs:

```

5 plugin(s) were loaded in legacy mode. Please visit https://fbflipper.com/docs/extending/sandy-migration to learn how to migrate these plugins to the new Sandy architecture: 
Hermes Debugger (RN) (id: Hermesdebuggerrn)
KaiOS RAM graph (id: kaios-graphs)
Layout (id: Inspector)
LeakCanary (id: LeakCanary)
Redux Debugger (id: flipper-plugin-redux-debugger) 
```

**Comment by machadogj** [comment] 2022-09-30 22:54
@simonkarmy do you have any updates or workarounds for this?

**Comment by jk-gan** [comment] 2022-10-01 02:49
Let me take a look on this weekend.

**Comment by jk-gan** [comment] 2022-10-02 17:32
After some testing, I think there are some changes in `react-native-flipper` >= 0.163.0 causing the issue. Downgrading to `0.162.0` works for me. I suspect the root cause is [this commit message](https://github.com/facebook/flipper/commit/73b6f93f90021488d6e2e724f37906b99f2b0cd0).

**Comment by machadogj** [comment] 2022-10-03 13:59
hi @jk-gan, thanks for looking at this.

I changed the package.json, the Podfile, and downloaded the Flipper application, all using version `0.162.0`, but I still have the same error.

Am I missing any steps? 🤔

**Comment by jk-gan** [comment] 2022-10-06 13:20
I wonder react-native 0.69 will have this issue or not, I should find a day to test it.

**Comment by jk-gan** [comment] 2023-02-25 06:05
`redux-flipper` seems to work with the the latest version of `react-native-flipper` now (v0.182.0 currently). 

<img width="2433" alt="Screenshot 2023-02-25 at 1 59 42 PM" src="https://user-images.githubusercontent.com/7545747/221341488-b8ac7692-9250-48fd-955a-21f345ef010d.png">

I'll close this issue. Feel free to re-open if the issue still occurring.

**Closed by jk-gan** 2023-02-25 06:05 UTC

**Comment by AlexSobiloffSonos** [comment] 2023-03-20 22:48
First, thanks for the plugin.

I'm experiencing this issue with rn 0.71.1 and flipper 0.186. flipper tells me:
```
The plugins below are installed in Flipper, but not available for the selected device / application. Hover the plugin info box to find out why.
```
Then when hovering the info icon next to the plugin name
```
Plugin 'Redux Debugger' is unavailable
Plugin 'Redux Debugger' is not supported by the selected application 'My App' (iOS).
```
This was working when we were on RN 0.68 and Flipper 125.

**Comment by nazmeln** [comment] 2023-06-13 10:01
Hey @AlexSobiloffSonos 
I had the same issue("react-native": "0.71.6"), and adding the following into Podfile fixes it. Also, please make sure to add the line below conditionally if you're using any CI/CD tools.

pod 'react-native-flipper', path: '../node_modules/react-native-flipper'
